name: Post Welcome comment
on:  
  pull_request:
    types: [opened]
jobs:   
  build:
    name: Post welcome comment
    runs-on: ubuntu-latest
    steps:
      - run: gh pr commecnt $PR_URL --body "Welcome to the repo!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
